### ISSUE TITLE
Syntax highlighting parser error

### ISSUE THREAD

**Issue by jon-whit** [openfga/vscode-ext#207]
In `v0.2.20` I notice a syntax highlighting bug. 

<img width="1108" alt="Screenshot 2024-04-01 at 10 21 26 AM" src="https://github.com/openfga/vscode-ext/assets/2899204/1927ad04-a806-4431-914b-0bfd50144741">

It looks like the parser is not accurately recognizing the closing `]` of the type restriction definition.

**Comment by jon-whit** [comment]
Reloaded VSCode and everything worked fine.  No action needed.

**Comment by jon-whit** [comment]
A reload/restart fixed the original reported issue in the original description, but I'm seeing the issue again with models involving conditions.
<img width="1602" alt="Screenshot 2024-04-01 at 10 37 11 AM" src="https://github.com/openfga/vscode-ext/assets/2899204/a3ed8175-a830-432b-ad41-9034a78060ef">

**Comment by d-jeffery** [comment]
Exception coming from `language`  with  column: { start: 0, end: 1 }. 

```
ModelValidationSingleError: condition-not-defined error at line=8, column=0: `c` is not a defined condition in the model.
    at constructValidationError (/Users/daniel.jeffery/VSCodeProjects/vscode-ext/server/out/server.node.js:25940:12)
    at createInvalidConditionNameInParameterError (/Users/daniel.jeffery/VSCodeProjects/vscode-ext/server/out/server.node.js:25735:17)
    at ExceptionCollector.raiseInvalidConditionNameInParameter (/Users/daniel.jeffery/VSCodeProjects/vscode-ext/server/out/server.node.js:26060:9)
    at childDefDefined (/Users/daniel.jeffery/VSCodeProjects/vscode-ext/server/out/server.node.js:11997:31)
    at relationDefined (/Users/daniel.jeffery/VSCodeProjects/vscode-ext/server/out/server.node.js:12109:13)
    at /Users/daniel.jeffery/VSCodeProjects/vscode-ext/server/out/server.node.js:12141:13
    at Array.forEach (<anonymous>)
    at modelValidation (/Users/daniel.jeffery/VSCodeProjects/vscode-ext/server/out/server.node.js:12137:88)
    at validateJSON (/Users/daniel.jeffery/VSCodeProjects/vscode-ext/server/out/server.node.js:12299:13)
    at Object.validateDSL (/Users/daniel.jeffery/VSCodeProjects/vscode-ext/server/out/server.node.js:12325:5) {
  properties: {
    msg: '`c` is not a defined condition in the model.',
    file: undefined,
    line: { start: 8, end: 8 },
    column: { start: 0, end: 1 }
  },
  type: 'condition-not-defined',
  line: { start: 8, end: 8 },
  column: { start: 0, end: 1 },
  msg: '`c` is not a defined condition in the model.',
  file: undefined,
  metadata: {
    symbol: 'c',
    errorType: 'condition-not-defined',
    module: undefined,
    relation: 'viewer',
    type: 'document'
  }
}```

**Comment by d-jeffery** [comment]
Fix: https://github.com/openfga/language/pull/219 - error occurred when condition name was a single character long.

This same codeblock is a pattern else where, but this change + test looks fixed.
